-- Retrieval Recovery Copilot — public MVP schema v3
-- Run this AFTER verifying the existing photo_embeddings/retrieval_events setup.

create extension if not exists vector with schema extensions;

alter table public.photo_embeddings
  add column if not exists embedding_model text,
  add column if not exists embedded_at timestamptz;

alter table public.photo_embeddings enable row level security;
revoke all on table public.photo_embeddings from anon, authenticated, public;

create table if not exists public.photo_catalog (
  id text primary key,
  storage_path text not null unique,
  public_url text not null,

  title text,
  creator text,
  creator_url text,

  license text not null,
  license_version text,
  license_url text,
  attribution text,

  provider text,
  source text,
  source_id text,
  source_url text,
  original_url text,

  width integer,
  height integer,

  tags jsonb not null default '[]'::jsonb,
  retrieval_metadata jsonb not null default '{}'::jsonb,
  source_metadata jsonb not null default '{}'::jsonb,

  embedding_status text not null default 'pending'
    check (embedding_status in ('pending','processing','ready','failed')),
  embedding_model text,
  embedded_at timestamptz,

  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists photo_catalog_embedding_status_idx
  on public.photo_catalog(embedding_status);
create index if not exists photo_catalog_active_idx
  on public.photo_catalog(active);

alter table public.photo_catalog enable row level security;
revoke all on table public.photo_catalog from anon, authenticated, public;

create table if not exists public.retrieval_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_name text not null,
  task_id text,
  candidate_id text,
  candidate_rank integer,
  dimension text,
  option text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists retrieval_events_session_idx
  on public.retrieval_events(session_id);
create index if not exists retrieval_events_event_idx
  on public.retrieval_events(event_name);

alter table public.retrieval_events enable row level security;
revoke all on table public.retrieval_events from anon, authenticated, public;

create table if not exists public.benchmark_tasks (
  task_id text primary key,
  name text not null,
  difficulty text not null check (difficulty in ('easy','medium','hard')),
  user_memory text not null,
  target_photo_id text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists benchmark_tasks_active_idx
  on public.benchmark_tasks(active);

alter table public.benchmark_tasks enable row level security;
revoke all on table public.benchmark_tasks from anon, authenticated, public;

-- Replace the earlier return shape so candidates include provenance + retrieval metadata.
drop function if exists public.match_photo_embeddings(vector, integer);

create function public.match_photo_embeddings(
  query_embedding vector(768),
  match_count integer default 40
)
returns table (
  id text,
  similarity double precision,
  storage_path text,
  public_url text,
  title text,
  creator text,
  creator_url text,
  license text,
  license_version text,
  license_url text,
  attribution text,
  provider text,
  source text,
  source_url text,
  tags jsonb,
  retrieval_metadata jsonb
)
language sql
stable
as $$
  select
    pe.id,
    (1 - (pe.embedding <=> query_embedding))::double precision as similarity,
    pc.storage_path,
    pc.public_url,
    pc.title,
    pc.creator,
    pc.creator_url,
    pc.license,
    pc.license_version,
    pc.license_url,
    pc.attribution,
    pc.provider,
    pc.source,
    pc.source_url,
    pc.tags,
    pc.retrieval_metadata
  from public.photo_embeddings pe
  join public.photo_catalog pc on pc.id = pe.id
  where pc.active = true and pc.embedding_status = 'ready'
  order by pe.embedding <=> query_embedding
  limit greatest(1, least(match_count, 100));
$$;

revoke execute on function public.match_photo_embeddings(vector, integer)
  from public, anon, authenticated;
grant execute on function public.match_photo_embeddings(vector, integer)
  to service_role;
