"use client";
import { useEffect, useState } from "react";

function session(){const k="rr_session";let v=localStorage.getItem(k);if(!v){v=crypto.randomUUID();localStorage.setItem(k,v)}return v}
async function track(event:string,extra:any={}){try{await fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event,sessionId:session(),...extra})})}catch{}}

export default function Test(){
  const [task,setTask]=useState<any>(null);const [cands,setCands]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState("");const [recovery,setRecovery]=useState<any>(null);const [activeClues,setActiveClues]=useState<any[]>([]);const [mode,setMode]=useState<"control"|"treatment">("treatment");
  async function load(){setLoading(true);setMsg("");setRecovery(null);setActiveClues([]);const r=await fetch("/api/test-task");setTask(await r.json());setCands([]);setLoading(false)}
  async function find(nextClues:any[]=activeClues){setLoading(true);await track("retrieval_started",{metadata:{mode}});await track("memory_submitted",{taskId:task.taskId});const r=await fetch("/api/retrieve",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({memory:task.userMemory,activeClues:nextClues,sessionId:session()})});const d=await r.json();if(!r.ok){setMsg(d.error||"Retrieval failed");setLoading(false);return}setCands(d.candidates||[]);setMsg(d.failure?.reason||"");setRecovery(mode==="treatment"?d.recovery:null);setLoading(false)}
  async function choose(id:string,rank:number){await track("candidate_clicked",{taskId:task.taskId,candidateId:id,rank});const r=await fetch("/api/test-result",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:task.taskId,candidateId:id,sessionId:session()})});const d=await r.json();setMsg(d.success?"✓ Correct photo retrieved. This counts as successful retrieval.":"That candidate was not the intended photo. Continue recovery or inspect another candidate.")}
  useEffect(()=>{load()},[]);
  return <main className="wrap"><div className="eyebrow">Controlled evaluation · target hidden</div><h1>Test retrieval with a hidden target</h1>
    <div className="row"><button className={mode==="control"?"primary":"secondary"} onClick={()=>setMode("control")} disabled={loading}>Control: single-pass</button><button className={mode==="treatment"?"primary":"secondary"} onClick={()=>setMode("treatment")} disabled={loading}>Treatment: recovery copilot</button><button className="secondary" onClick={load}>New hidden task</button></div>
    {task&&<div className="card"><div className="section-title"><h2>{task.name}</h2><span className="pill">{task.difficulty}</span></div><p className="lead" style={{fontSize:17}}>{task.userMemory}</p><button className="primary" onClick={()=>find([])} disabled={loading}>{loading?"Working...":"Run retrieval"}</button></div>}
    {msg&&<div className="card"><div className={msg.startsWith("✓")?"success":"banner warn"}>{msg}</div></div>}
    {cands.length>0&&<div className="card"><div className="section-title"><h2>Candidate photos</h2><span className="pill">Choose only if you believe it matches</span></div><div className="candidates">{cands.slice(0,12).map((c,i)=><button key={c.id} className="candidate" onClick={()=>choose(c.id,i+1)}><img src={c.image} alt="Candidate"/><div className="candidate-body"><span className="score">#{i+1}</span><div className="candidate-title">{c.title || "Possible match"}</div><div className="candidate-meta">{c.attribution || "Open-licensed photo"}</div></div></button>)}</div><div className="row" style={{marginTop:14}}><button className="secondary" onClick={()=>{track("none_of_these",{taskId:task.taskId});setMsg("No candidate selected. Continue with the recovery step.")}}>None of these</button></div></div>}
    {recovery&&<div className="card"><div className="section-title"><h2>Recover the search</h2><span className="pill">One high-value clue</span></div><p className="sub">{recovery.question}</p><div className="chips">{recovery.options.map((o:string)=><button className="chip" key={o} onClick={()=>{const next=[...activeClues,{dimension:recovery.dimension,value:o,certainty:o==="Not sure"?0:1,explicit:true}];setActiveClues(next);track("recovery_option_selected",{taskId:task.taskId,dimension:recovery.dimension,option:o});find(next)}}>{o}</button>)}</div></div>}
    <p className="footer">The target photo is never sent to the browser. In test mode, success is checked server-side against hidden ground truth. Real, openly licensed demonstration photos. The benchmark target is hidden server-side.</p></main>
}
